@startuml ah_sound

actor "사용자 이벤트" as loader
participant "load_audio()" as prep
participant "estimate_pitch_spice_only()" as model
participant "filter_pitch()" as filter
participant "custom_moving_std()" as customized_std
participant "analyze_pitch_stability()" as anal

== 전처리 모듈 ==

loader -> anal: filepath, sample_rate
anal -> prep: filepath, sample_rate
prep -> anal: audio, sr

== 특징 추출 모듈 ==

anal -> model: audio, sr
model -> anal: pitch

== 후처리 모듈 ==

anal -> filter: pitch, confidence, threshold
filter -> anal: filtered_pitch
anal -> customized_std: filtered_pitch, window_size
customized_std -> anal: pitch_std
anal -> loader: mono_duration

@enduml
