@startuml ptk_sequence
title 퍼터커 반복하기

participant "main" as loader
participant "audio_preprocess()" as audio_file_transformation
participant "wav_padding()" as padding
participant "x_data_preprocess()" as preprocess
participant "build_ptk_model()" as model_builder
participant "model.fit()" as model_fit
participant "pred_preprocess()" as pred_preprocess
participant "load_model()" as model_pred
participant "ptk_each()" as ptk_each_pred
participant "ptk_whole()" as ptk_whole_pred
participant "model_whole.predict()" as model_whole
participant "model_each.predict()" as model_each
participant "model_comm.get_file_lst()" as model_comm

== 데이터 준비 ==
loader -> model_comm: assess_type, question_cd, question_no, order_num 
model_comm -> loader: wav_label_pairs[path,label]
== 전처리 과정 ==
loader -> preprocess: wav_file, sr, n_mels
preprocess -> audio_file_transformation: path
audio_file_transformation -> preprocess: mel_db1, round(duration,3), length
preprocess -> padding: wav_file, wav_max_len
padding -> preprocess: padded
preprocess -> loader: padded

== 학습 과정(단일 음정) ==
loader -> model_builder
model_builder -> loader: model
loader -> model_fit: x_train, y_train, epochs, batch_size, x_valid, y_valid
model_fit -> loader: model_each

== 학습 과정(다중 음정) ==
loader -> model_builder
model_builder -> loader: model
loader -> model_fit: x_train, y_train, epochs, batch_size, x_valid, y_valid
model_fit -> loader: model_whole

== 예측 과정 ==
loader -> ptk_whole_pred: filepath
ptk_whole_pred -> pred_preprocess: filepath
pred_preprocess -> ptk_whole_pred: ptk_x_data
ptk_whole_pred -> model_pred: keras
model_pred -> ptk_whole_pred: model_whole
ptk_whole_pred -> model_whole: ptk_x_data
model_whole -> ptk_whole_pred : pred
ptk_whole_pred -> loader: pred

loader -> ptk_each_pred: filepath
ptk_each_pred -> pred_preprocess: filepath
pred_preprocess -> ptk_each_pred: ptk_x_data
ptk_each_pred -> model_pred: keras
model_pred -> ptk_each_pred: model_each
ptk_each_pred -> model_each: ptk_x_data
model_each -> ptk_each_pred : pred
ptk_each_pred -> loader: pred


@enduml