@startuml ptk_prep
title 퍼터커 음성 신호 처리 시퀀스 다이어그램

participant "Data Loader" as loader
participant "audio_preprocess(wav, sr, n_mels)" as audio_file_transformation
participant "wav_padding(wav, wav_max_len)" as padding
participant "build_ptk_model" as model_builder
participant "Model Training" as training
participant "ptk_each" as each
participant "ptk_whole" as ptk

== 전처리 과정 ==

loader -> audio_file_transformation: wav_file, sr, n_mels
audio_file_transformation --> padding: mel_db, duration, length

padding -> preprocess: mel_db, wav_max_len
preprocess --> padding: padded_wav
padding --> loader: preprocessed_data

@enduml