version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - OMP_NUM_THREADS=1
    stdin_open: true
    tty: true